version: '3.8'
# Development environment override
services:
  
  localhost:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      DB_HOST: localhost
      MYSQL_DATABASE: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
    - 3306:3306
    volumes:
    - ./db-dump:/docker-entrypoint-initdb.d